### ISSUE TITLE
Importing to Unity Instructions

### ISSUE THREAD

**Issue by Roar1827** [zhuchun/cjk#1]
Thank you for your work in creating this. I am trying to import to unity as suggested in the readme. I encounter the following error:

![Screen Shot 2020-03-09 at 11 29 55 AM](https://user-images.githubusercontent.com/4673180/76229984-6b1c7700-61f9-11ea-82e2-85d70ce0f29c.png)

It does not seem to recognize the asset as a font asset. Any ideas?

**Comment by zhuchun** [comment]
> Thank you for your work in creating this. I am trying to import to unity as suggested in the readme. I encounter the following error:
> 
> ![Screen Shot 2020-03-09 at 11 29 55 AM](https://user-images.githubusercontent.com/4673180/76229984-6b1c7700-61f9-11ea-82e2-85d70ce0f29c.png)
> 
> It does not seem to recognize the asset as a font asset. Any ideas?

Hi, I'm afraid this file no longer usable, as I created it 4 years ago and TMP itself was a plugin, but now TMP is a native package so associated script may be changed.

**Comment by zhuchun** [comment]
In case you want to create a CJK asset yourself, here's the info https://www.unicode.org/Public/5.0.0/ucd/Unihan.html
You can find a code point range table right below the first page, that's the Unicode range of CJK you want to fill inside TMP.

**Comment by Roar1827** [comment]
Thank you @zhuchun - I was able to create a font using noto.

**Comment by tecraveiro** [comment]
> Thank you @zhuchun - I was able to create a font using noto.

Would you mind sharing how or dropping the asset here? I do not understand what I need to enter form the above linked Unihan page into TMP.

**Comment by zhuchun** [comment]
> Would you mind sharing how or dropping the asset here? I do not understand what I need to enter form the above linked Unihan page into TMP.

It all depends on what you need. Unihan has everything inside, but it's not ideal for mobile games as it contains lots of characters, IIRC, over 30k for Chinese and Korean. It's only useful when you want to create a chat room, so maybe it's not your choice.

On the other hand, you can Google something like "Common Chinese Characters", it's a text file that contains only about 6k characters but could cover most daily usages without any problem. Also, you can easily give that text file to TMP and say "Hey, generate a font file with these characters". Maybe Korean and Japanese have similar text files.

I would suggest you start from the common one and grab some random Wiki pages in your target language to see if there's any unwanted '口'
